version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  orders-svc:
    build: ./packages/orders-svc
    environment:
      DATABASE_URL: ${ORDERS_DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/orders?schema=public}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
      PORT: ${ORDERS_PORT:-3001}
    depends_on: [postgres, rabbitmq]
    ports: ["3001:3001"]

  inventory-svc:
    build: ./packages/inventory-svc
    environment:
      DATABASE_URL: ${INVENTORY_DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/inventory?schema=public}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
      PORT: ${INVENTORY_PORT:-3003}
    depends_on: [postgres, rabbitmq]
    ports: ["3003:3003"]

  products-svc:
    build: ./packages/products-svc
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
      PORT: ${PRODUCTS_PORT:-3002}
    depends_on: [rabbitmq]
    ports: ["3002:3002"]

  payments-svc:
    build: ./packages/payments-svc
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672}
      PORT: ${PAYMENTS_PORT:-3004}
    depends_on: [rabbitmq]
    ports: ["3004:3004"]

  storefront:
    build: ./apps/storefront
    environment:
      NEXT_PUBLIC_ORDERS_URL: http://localhost:3001
    ports: ["3000:3000"]
    depends_on: [orders-svc]

volumes:
  pgdata:
